Feat: allow setting editorial workflow PR label prefix
netlify/netlify-cms pull request #4181
Opened 2020-08-21 09:45 UTC by KancerEzeroglu

closes #3977 

**Summary**
When you are using editorial workflow, status labels are created with hardcoded `netlify-cms/` prefix. 
With this PR, we enable you to add a custom prefix to config.yml which overwrites the default hardcoded one.
I only did changes for GitHub. If I am in the right direction, I'll make changes for others (GitLab, bitbucket) as well.

**Test plan**
Unit tests

**A picture of a cute animal (not mandatory but encouraged)**
my first PR 👯 

![firsttime](https://user-images.githubusercontent.com/1583507/90877027-b7bcce80-e3a3-11ea-960d-b31243b21222.gif)

2020-08-30 16:01 UTC, erezrokah requested changes
Thanks @KancerEzeroglu. Nice work.
There are still some places you need to pass the prefix (mostly for non GitHub backends).

2020-08-30 16:01 UTC, erezrokah commented on packages/netlify-cms-lib-util/src/APIUtils.ts
> +export const isCMSLabel = (label: string, labelPrefix = '') =>
I recommend removing the default value for `labelPrefix`, then running `yarn test` to see all the places you should be passing the prefix

2020-08-31 09:07 UTC, KancerEzeroglu commented on dev-test/config.yml
> +  - name: pages # a nested collection
I removed this part.

2020-09-06 16:54 UTC, erezrokah commented
@KancerEzeroglu, I moved the config under the `backend` section, added docs and added more explicit names to some tests.

2020-09-06 18:13 UTC, merged

2020-09-07 09:12 UTC, KancerEzeroglu commented
Thanks @erezrokah 😄 
I will review the changes you have made to better understand the code and see where I am missing.