Fix SVGs when using local_backend
netlify/netlify-cms pull request #4206
Opened 2020-08-25 04:03 UTC by zmre

**Summary**

When using `local_backend: true` and `npx netlify-cms-proxy-server`, SVG images are broken in the media browser and entrycard interfaces. Most of the other backends have SVG detection and add a filetype to the `File` blob. This brings that fix to the proxy backend. 

There may be a bigger refactor here that would reduce duplication of code across backends, but I'm not the one to take that on.

The broken images were driving me nuts.

Before:

<img width="1202" alt="Screen Shot 2020-08-24 at 9 54 08 PM" src="https://user-images.githubusercontent.com/71791/91121190-8585c800-e654-11ea-8958-3a1b949f00b1.png">

After:

<img width="1197" alt="Screen Shot 2020-08-24 at 9 54 21 PM" src="https://user-images.githubusercontent.com/71791/91121213-8fa7c680-e654-11ea-9979-af7ee3839b03.png">

**Test plan**

This is a two line code change that adds an option to the `new File`. I did not add a unit test, but I did build the change and confirm the fix works.

**A picture of a cute animal (not mandatory but encouraged)**

![IMG_0032](https://user-images.githubusercontent.com/71791/91121534-3c824380-e655-11ea-85bc-f908794ce467.jpeg)

2020-08-25 17:59 UTC, zmre commented
The only "X" here is the lack of a label, which I can't add. I'd recommend labeling this as a bug.

2020-08-26 12:58 UTC, erezrokah requested changes
Thanks @zmre, very nice fix.
Any chance we can re-use https://github.com/netlify/netlify-cms/blob/f950a8ea5145f6deb0de1fa30f66617e903d22ac/packages/netlify-cms-lib-util/src/implementation.ts#L249 to avoid duplication?

2020-08-26 16:48 UTC, zmre commented
Sure. I hesitated to do that originally because I didn't like creating the blob without a type in it, but I guess it doesn't matter in this instance. I updated to use the blob approach and the `blobToFileObj` function and tested locally to confirm it works.

2020-08-26 17:00 UTC, zmre commented
Well, hmmm, the build is failing and I seriously doubt it has anything to do with my changes (and not just because they build fine for me or because the error has nothing to do with the module I changed).  Is this just a case of needing to rerun the checks?

2020-08-26 17:03 UTC, erezrokah commented
> Is this just a case of needing to rerun the checks?

Yes, I'm looking into it, thanks 😄

2020-08-27 08:01 UTC, erezrokah approved these changes

2020-08-27 08:02 UTC, merged