Create Docs: Guides “gridsome”
netlify/netlify-cms pull request #4433
Opened 2020-10-10 00:13 UTC by milos5593

2020-10-25 15:08 UTC, erezrokah requested changes
@milos5593 Thank you for creating this guide. Sorry for my late response.
Added a few comments - most of them are minor.
The main issue is to have this guide aligned with other guides with regards to pushing content to GitHub and connecting to Netlify (git-gateway and Identity).

2020-10-25 15:08 UTC, erezrokah commented on website/content/docs/gridsome.md
> +Please read [gridsome-plugin-netlify-cms](https://gridsome.org/plugins/gridsome-plugin-netlify-cms), [transformer-remark](https://gridsome.org/plugins/@gridsome/transformer-remark) for more informati
```suggestion
Please read [gridsome-plugin-netlify-cms](https://gridsome.org/plugins/gridsome-plugin-netlify-cms), [transformer-remark](https://gridsome.org/plugins/@gridsome/transformer-remark) for more information.
```

2020-10-25 15:08 UTC, erezrokah commented on website/content/docs/gridsome.md
> +</html>
```suggestion
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Netlify CMS</title>
  </head>
  <body>
    <script src="index.js" type="module"></script>
  </body>
</html>

```

2020-10-25 15:08 UTC, erezrokah commented on website/content/docs/gridsome.md
> +  name: github
Can we use `git-gateway` like the other guides for consistency?

2020-10-25 15:08 UTC, erezrokah commented on website/content/docs/gridsome.md
> +## Add your repo to Netlify
Should we add the missing `Push to GitHub` part like the other guides?
https://www.netlifycms.org/docs/gatsby/#push-to-github

2020-10-25 18:00 UTC, milos5593 commented
@erezrokah mo problems, I'll make the changes in a couple of day's, need to finalize a project for a client.

2020-10-25 18:07 UTC, erezrokah commented
> I'll make the changes in a couple of day's, need to finalize a project for a client.

Sure no rush :)

2020-10-31 23:03 UTC, milos5593 commented
@erezrokah  Let me know if this works.

2020-11-02 11:54 UTC, erezrokah approved these changes
Thanks @milos5593, I added another commit to fix some syntax highlighting issues and replaced GitHub authentication with `Identity` and `git-gateway`  as the `config.yml` uses `backend: git-gateway`.
The latter also aligns this guide with the other ones in regards with authentication method.

2020-11-02 12:04 UTC, merged