fix(typings): make 'status' state slice more typesafe
netlify/netlify-cms pull request #4709
Opened 2020-12-13 21:48 UTC by smashercosmo

**Summary**

Make 'status' state slice more typesafe by providing proper StatusAction type

**Test plan**

Tests are not needed

2020-12-14 11:32 UTC, erezrokah requested changes
Thanks @smashercosmo, looks great.
I've made two minor suggestions to the default state so it will reflect an non error status.
See https://github.com/netlify/netlify-cms/blob/2abeacfaee774951924d81536dc7db7001d3af09/packages/netlify-cms-core/src/actions/status.ts#L51
Please let me know what you think

2020-12-14 11:32 UTC, erezrokah commented on packages/netlify-cms-core/src/reducers/status.ts
> +    auth: { status: false },
```suggestion
    auth: { status: true },
```

2020-12-14 11:32 UTC, erezrokah commented on packages/netlify-cms-core/src/reducers/status.ts
> +    api: { status: false, statusPage: '' },
```suggestion
    api: { status: true, statusPage: '' },
```

2020-12-14 14:01 UTC, smashercosmo commented
@erezrokah Should these also be changed then https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/backend.ts#L337-L338 ?

2020-12-14 14:39 UTC, erezrokah commented
> @erezrokah Should these also be changed then https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/backend.ts#L337-L338 ?

Good point.- I think that default value can be removed since the first iteration of the loop will overwrite it anyway. We might need to make TypeScript happy since it might report an error of returning an uninitialized value.

2020-12-14 15:01 UTC, smashercosmo commented
TS does yell if you remove default value. So, I'll just change default status value to 'true' for consistency.

2020-12-14 15:06 UTC, smashercosmo commented
I would also make condition inside the loop more explicit, so instead of ```if (Object.values(status).every(s => s.status === true)) {...}``` I would just ```if (status.auth.status && status.api.status) {...}```. Easier to understand what's going on.

2020-12-14 15:25 UTC, erezrokah commented
> I would also make condition inside the loop more explicit, so instead of `if (Object.values(status).every(s => s.status === true)) {...}` I would just `if (status.auth.status && status.api.status) {...}`. Easier to understand what's going on.

I understand but we might add more indicators in the future. I could go either way, but if you do make that change please verify all backends return that structure.

2020-12-14 15:35 UTC, smashercosmo commented
Ok, I'll leave it as is then

2020-12-14 15:53 UTC, smashercosmo commented
done

2020-12-15 10:38 UTC, erezrokah approved these changes

2020-12-15 10:39 UTC, merged