fixes #5557: modify status button to show the current status
netlify/netlify-cms pull request #5574
Opened 2021-07-02 19:36 UTC by pcanof

**Summary**
The set status dropdown is confusing for users becuase they cannot see what the current status is without opening the dropdown. To solve this issue I take the option two that mention in issue #5557 because add another component to the toolbar would cause a mess. To do this I only change the way that Status Menu Button shows the current status of the post and I add a text that says "Current Status:", that maybe it needs to be added to the file where is all the words for translate to another language.

**Test plan**
well, I add some if conditionals to evaluate the status of the post and depending of that status is the name that will be appear in the dropdown button with an addition of the sentence "Current Status:" And the result you can see it in the following picture.

**A picture of a cute animal (not mandatory but encouraged)**
<img width="1432" alt="Screen Shot 2021-07-02 at 1 16 16 PM" src="https://user-images.githubusercontent.com/37887903/124320038-68553c00-db38-11eb-9b32-56e0cab6a32b.png">

2021-07-06 17:58 UTC, erezrokah requested changes
Thanks @pchorus! Great progress.

I've added some comments and commits to address them. I've also fixed a bug that caused `isUpdatingStatus` and `isPublishing` to always be `undefined`

Please let me know what you think, cc @bradystroud

2021-07-06 17:58 UTC, erezrokah commented on packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
> +      buttonText = isUpdatingStatus ? t('editor.editorToolbar.updating') : t('editor.editorToolbar.setStatus');
I believe this will be dead code after this PR. Have to managed to reach the block inside this `else`?

Also, `setStatus` can probably be removed

2021-07-06 17:58 UTC, erezrokah commented on packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
> +          <StatusButton>{`Current Stauts: ${buttonText}`}</StatusButton>
We should not use hard coded strings. Instead add a translation message and key to:
https://github.com/netlify/netlify-cms/blob/574025fd649d49f70650a6112617642a6cb24f07/packages/netlify-cms-locales/src/en/index.js

and use the `t` to get the translation (see other usages in this file).

2021-07-06 22:33 UTC, bradystroud commented
Hi @erezrokah @pcanof,

This is looking really good. 😄

2021-07-07 08:19 UTC, erezrokah approved these changes

2021-07-07 08:20 UTC, merged