Export local backend middlewares in proxy server
netlify/netlify-cms pull request #5852
Opened 2021-09-30 03:50 UTC by mmkal

**Summary**

For `local_backend` users with an existing express server already running, who would like to avoid having to run yet another server on another port to have _some_ parts of the functionality work. With this change, it's possible to use the middleware directly, without creating a whole server in a new process:

```js
const handler = require('netlify-cms-proxy-server/dist/middlewares').localFsMiddleware({
  repoPath: ...,
  logger: console,
})

handler(req, res)
```

👆 the above works both with express and in a next.js api handler.

**Test plan**

So, my plan was _just_ to export it to begin with. My hope was that it could be an undocumented part of the API surface of this library and therefore subject to change without a major bump, but it would be useable for those who happen to know it's there.

Having it be an official part of the "real" API surface would be a comparatively change: there would need to be a separate entrypoint for the middleware module part of the library, which doesn't have the side-effect of trying to start a server (and it'd probably be a good idea to generate `.d.ts` files and write documentation, recommended usage, etc., and maybe get rid of the type dependency on winston in the params). And I can't see the harm in just doing this small change for now.

**Checklist**

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] Code is formatted via running `yarn format`.
- [x] Tests are passing via running `yarn test`.
- [ ] The status checks are successful (continuous integration). Those can be seen below.

**A picture of a cute animal (not mandatory but encouraged)**

![telegram-cloud-photo-size-4-5958282957670167938-y](https://user-images.githubusercontent.com/15040698/135383848-9f3a651b-0233-4b03-a8b6-39586e099346.jpg)

(my parents' cat)

2021-09-30 09:36 UTC, erezrokah requested changes
Hi @mmkal, thanks for the PR ❤️  We already export methods to register a specific middleware, see https://github.com/netlify/netlify-cms/pull/3361.
Could you use that approach?

Also, the approach in your PR is missing some init logic to setup schema validation and other required middlewares like CORS and JSON parsing. See `registerCommonMiddlewares`

2021-09-30 12:03 UTC, mmkal commented
Hey @erezrokah, all very fair points. I was taking a shortcut to do the bare minimum possible to get it working with next.js - i.e. in a context where there is no `app` with `.post` or `.use` methods, so traditional middleware basically isn't supported. But yes it does mean there's no schema validation, cors, json-parsing or logging. Those were all ok to miss because respectively, the client is only sending valid requests, we happen to not need cors, next.js has already done json-parsing for us, and we are able to do our own logging.

I think I could probably make it work with the existing exports by passing in a fake express app from the handler, but that would be quite brittle.

An alternative - could the `dist` folder be generated using `tsc` rather than webpack? Given it's a node library/CLI I can't see why it would need to be bundled or minified. There'd be a few benefits:

- users could import from `dist/middlewares/whatever`, at their own risk
- type declarations would come for free
- no need to maintain the webpack config anymore! (This is only a benefit because you already have a tsconfig, otherwise you'd be swapping one for the other)

2021-09-30 12:52 UTC, mmkal commented
Update: got it working with the existing exports by passing in a fake `app`. Behold the hoop-jumping:

```js
export default async (req, res) => {
  const netlifyCmsProxyServer =
    require('netlify-cms-proxy-server/dist/middlewares') as typeof import('netlify-cms-proxy-server/src/middlewares')
  const path = require('path')
  const handlers: Function[] = []
  process.env.GIT_REPO_DIRECTORY = path.join(process.cwd(), '../..')

  const fakeApp = {
    use: () => {}, // skip next.js 
    post: (_path: string, handler: Function) => handlers.push(handler),
  }
  
  netlifyCmsProxyServer.registerLocalFs(fakeApp as any, { logLevel: 'error' })
  
  for (const handler of handlers) {
    let nextCalled = false
    const next = () => (nextCalled = true)
    await handler(req, res, next)
    if (!nextCalled) {
      break
    }
  }
}
```

The above could easily break if the library changes some parts of its implementation, so I'd still be in favour of exporting the extra functions. But I might play around with a `tsc` build alternative instead.

2022-04-14 12:16 UTC, erezrokah commented
Closing in favor of https://github.com/netlify/netlify-cms/pull/5856. I do believe using `tsc` is the right approach, given that we don't break existing consumers (we'll need to verify).

2022-04-14 12:16 UTC, closed without merging